### PR TITLE
Fix pip version number

### LINKED ISSUE #5: pip indicates version 0.0.0 is installed
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When I do `conda create -y -n outdated outdated=0.2.2 && conda activate outdated && pip list | grep outdated`, it returns:
```bash
outdated           0.0.0
```

Ironically, `outdated` looks outdated. This is problematic when I run `pip check`, one of my conda packages needs `outdated=0.2.2` and the check fails. 

### Installed packages

```shell
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
brotli-python             1.1.0           py312h30efb56_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
charset-normalizer        3.3.1              pyhd8ed1ab_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.43.2               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
littleutils               0.2.2                      py_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
openssl                   3.1.4                hd590300_0    conda-forge
outdated                  0.2.2              pyhd8ed1ab_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.0          hab00c5b_0_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h2797004_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.7              pyhd8ed1ab_0    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
active environment : outdated
    active env location : /home/plumail/miniforge3/envs/outdated
            shell level : 2
       user config file : /home/plumail/.condarc
 populated config files : /home/plumail/miniforge3/.condarc
                          /home/plumail/.condarc
          conda version : 23.3.1
    conda-build version : 3.25.0
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __glibc=2.37=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /home/plumail/miniforge3  (writable)
      conda av data dir : /home/plumail/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/plumail/miniforge3/pkgs
                          /home/plumail/.conda/pkgs
       envs directories : /home/plumail/miniforge3/envs
                          /home/plumail/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Linux/5.14.0-1057-oem ubuntu/23.04 glibc/2.37 solver/libmamba conda-libmamba-solver/23.3.0 libmambapy/1.4.2
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by yut23**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Fixes #5.

Also adds a test to check the version at build time.
See https://conda.discourse.group/t/package-version-shown-as-0-0-0-with-dynamic-versioning-in-pyproject-toml/615/2 for  more details.

### CODE REVIEW

**Comment by yut23** [comment]
@conda-forge-admin, please rerender

**Comment by hoechenberger** [comment]
Thanks @yut23

**Comment by hoechenberger** [comment]
@yut23 would you like to become a maintainer of this feedstock?

**Comment by yut23** [comment]
No, I don't use this package myself; this was just a drive-by contribution.
I first ran into this pip version problem a few months ago in one of my own projects, and spent a while figuring it out. I helped fix it today for another package I help maintain, and I figured I'd search for open issues in other feedstocks and fix them as well.

**Pull request merged**
